export const GAMES = [
  { id: 'alias', title: 'Элиас', emoji: '🗣️', short: 'Объясняй слова, не называя их', players: '4+', time: '15–30 мин', category: 'объяснялки', hot: false },
  { id: 'never', title: 'Я никогда не…', emoji: '🙅', short: 'Узнай тайны друзей', players: '3+', time: '10–20 мин', category: 'вопросы', hot: true },
  { id: 'truth', title: 'Правда или действие', emoji: '🎯', short: 'Классика вечеринок', players: '3+', time: '∞', category: 'действия', hot: true },
  { id: 'whoofus', title: 'Кто из нас', emoji: '👥', short: 'Голосуй за самого-самого', players: '4+', time: '10–20 мин', category: 'голосование', hot: true },
  { id: 'spy', title: 'Шпион', emoji: '🕵️', short: 'Найди того, кто не знает локацию', players: '4+', time: '10–15 мин', category: 'детектив', hot: false },
  { id: 'crocodile', title: 'Крокодил', emoji: '🐊', short: 'Покажи слово жестами', players: '3+', time: '15–30 мин', category: 'объяснялки', hot: false },
  { id: 'five', title: '5 секунд', emoji: '⏱️', short: 'Назови три за 5 секунд', players: '2+', time: '10–20 мин', category: 'скорость', hot: true },
  { id: 'memes', title: 'Мем-батл', emoji: '😂', short: 'Подбери лучший мем к ситуации', players: '3+', time: '15–25 мин', category: 'мемы', hot: false },
  { id: 'whoami', title: 'Кто я?', emoji: '❓', short: 'Угадай персонажа по вопросам', players: '2+', time: '10–20 мин', category: 'угадайка', hot: false },
  { id: 'most', title: 'Кто скорее всего…', emoji: '📊', short: 'Голосование за самого вероятного', players: '4+', time: '10–15 мин', category: 'голосование', hot: true },
  { id: 'fact', title: 'Угадай факт о друге', emoji: '🔍', short: 'Правда или вымысел?', players: '3+', time: '15–25 мин', category: 'угадайка', hot: false },
  { id: 'mafia', title: 'Мафия', emoji: '🎭', short: 'Мирные против мафии', players: '6+', time: '20–40 мин', category: 'детектив', hot: true },
  { id: 'bunker', title: 'Бункер', emoji: '☢️', short: 'Кто выживет в ядерном бункере?', players: '4+', time: '30–60 мин', category: 'ролевые', hot: true },
  { id: 'associations', title: 'Ассоциации', emoji: '🧠', short: 'Объясни словом-ассоциацией', players: '3+', time: '10–20 мин', category: 'слова', hot: false },
  { id: 'hot_seat', title: 'Горячий стул', emoji: '🔥', short: 'Один отвечает — все спрашивают', players: '3+', time: '15–30 мин', category: 'вопросы', hot: false },
  { id: 'taboo', title: 'Табу', emoji: '🚫', short: 'Объясни слово без запрещённых', players: '4+', time: '15–25 мин', category: 'объяснялки', hot: false },
];
