export const GAMES = [
  {
    id: 'alias',
    title: 'Элиас',
    emoji: '🗣️',
    short: 'Объясняй слова, не называя их',
    players: '4+',
    time: '15–30 мин',
  },
  {
    id: 'never',
    title: 'Я никогда не…',
    emoji: '🙅',
    short: 'Узнай тайны друзей',
    players: '3+',
    time: '10–20 мин',
  },
  {
    id: 'truth',
    title: 'Правда или действие',
    emoji: '🎯',
    short: 'Классика вечеринок',
    players: '3+',
    time: '∞',
  },
  {
    id: 'whoofus',
    title: 'Кто из нас',
    emoji: '👥',
    short: 'Голосуй за самого-самого',
    players: '4+',
    time: '10–20 мин',
  },
  {
    id: 'spy',
    title: 'Шпион',
    emoji: '🕵️',
    short: 'Найди того, кто не знает локацию',
    players: '4+',
    time: '10–15 мин',
  },
  {
    id: 'crocodile',
    title: 'Крокодил',
    emoji: '🐊',
    short: 'Покажи слово жестами',
    players: '3+',
    time: '15–30 мин',
  },
  {
    id: 'five',
    title: '5 секунд',
    emoji: '⏱️',
    short: 'Назови три за 5 секунд',
    players: '2+',
    time: '10–20 мин',
  },
  {
    id: 'memes',
    title: 'Мем-батл',
    emoji: '😂',
    short: 'Подбери лучший мем к ситуации',
    players: '3+',
    time: '15–25 мин',
  },
  {
    id: 'whoami',
    title: 'Кто я?',
    emoji: '❓',
    short: 'Угадай персонажа по вопросам',
    players: '2+',
    time: '10–20 мин',
  },
  {
    id: 'most',
    title: 'Кто скорее всего…',
    emoji: '📊',
    short: 'Голосование за самого вероятного',
    players: '4+',
    time: '10–15 мин',
  },
  {
    id: 'fact',
    title: 'Угадай факт о друге',
    emoji: '🔍',
    short: 'Правда или вымысел?',
    players: '3+',
    time: '15–25 мин',
  },
];
